### PR TITLE
Skins in game + Saving ClientSettings

### PR DESCRIPTION
**Pull request by 2vb**
Added:
- Dedicated server profile route (To get skins in game)
- Saving user settings as a local file
- Discord command to give everything

### CODE REVIEW

**Comment by frauderik** [comment]
Discord command looks good 👍 I don't want to have local files as a method of client settings, rather using a cloudflare bucket / Amazon bucket. Once I am back from holiday I will merge the new command

**Review by ectrc — CHANGES_REQUESTED** [review]
Remove client settings I am going to implement Amazon CDN storage when I am back from vacation.

**Comment by ectrc** [comment]
Also skins in game would not work as you are using the client profile handler. I want to make a separate server handler to also implement save the world actions in the future.

**Review by ectrc — APPROVED** [review]
Thank you

**Pull request merged**
