### PR TITLE
Infinite patching fix

### PR DESCRIPTION
**Pull request by 2vb**
Fix *i think* for the stuck on patching and getting rate limited error

### CODE REVIEW

**Comment by 2vb** [comment]
Tested on 8.51 and 12.41

**Comment by RyanZuZi** [comment]
Can't build it.

C:\Users\Rzals\Desktop\Snow>go build
github.com/ectrc/snow/handlers

handlers\auth.go:30:11: syntax error: unexpected :, expected {
handlers\auth.go:35:18: syntax error: unexpected :, expected := or = or comma
handlers\auth.go:48:16: syntax error: unexpected :, expected := or = or comma
handlers\auth.go:49:9: syntax error: missing statement after label
handlers\auth.go:69:11: syntax error: missing statement after label
handlers\auth.go:119:9: syntax error: missing statement after label
handlers\auth.go:156:9: syntax error: missing statement after label
handlers\auth.go:178:9: syntax error: missing statement after label
handlers\auth.go:203:11: syntax error: missing statement after label
handlers\auth.go:216:13: syntax error: missing statement after label
handlers\auth.go:216:13: too many errors

C:\Users\Rzals\Desktop\Snow>

**Comment by 2vb** [comment]
My bad, should be fixed now

**Comment by RyanZuZi** [comment]
Thanks. Working fine now. I even tried the commit ecc just pushed and it still is spamming it. Will use this commit for now. Hopefully its fixed later down the line.

**Comment by ectrc** [comment]
# Not Comitting PR as of right now.
Please fix the merge conflict and also the line indents. Otherwise it will fuck up the entire file so I do not want to do that.
I am happy to merge your solution for the spamming of the API however not with the state of your project.

**Pull request closed without merging**
